apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MONGO_DB_NAME: bestbuy
  MONGO_URI: mongodb://admin:password@mongodb:27017/
  RABBITMQ_CONNECTION_STRING: amqp://rabbitmq
  QUEUE_NAME: order_queue
  PRODUCT_SERVICE_URL: http://product-service:3030
  ORDER_SERVICE_URL: http://order-service:3000