apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
    spec:
      containers:
        - name: makeline-service
          image: thomas4806/bestbuy-makeline-service:latest
          env:
            - name: RABBITMQ_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_CONNECTION_STRING
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URI
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_DB_NAME
            - name: QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: QUEUE_NAME